config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#home"
  get "profile", to: "pages#profile", as: :profile
  get "map", to: "pages#map"

  resources :cinemas, only: [:index, :show] do

    resources :reviews, only: [:new, :create] do
      resources :comments, only: [:create, :destroy]
      resources :votes, only: [:create, :destroy]
    end
    resources :favourites, only: [:create, :destroy]
  end
  resources :reviews, only: [:edit, :update, :destroy]
  resources :favourites, only: [:index, :destroy]

  resources :notifications, only: [:index, :destroy] do
    member do
      patch :mark_as_read
    end
  end

  # get "favourites/index"
  # get "favourites/create"
  # get "favourites/destroy"
  # get "reviews/new"
  # get "reviews/create"
  # get "reviews/edit"
  # get "reviews/update"
  # get "reviews/destroy"
  # get "cinemas/index"
  # get "cinemas/show"

  # get "notifications/index"
  # get "notifications/create"
  # get "notifications/destroy"
  # get "comments/create"
  # get "comments/destroy"
  # get "votes/create"
  # get "votes/destroy"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_bottom_navbar.html.erb
<!-- Bottom Navbar -->
<nav class="bottom_navbar navbar-light bg-light navbar-expand fixed-bottom">
  <div class="container-fluid">

    <%# Home  button %>
    <div>
      <%= link_to root_path, class: "bottom_navbar-link #{'active' if current_page?(root_path)}" do %>
        <i class="fa-solid fa-house"></i>
      <% end %>
    </div>

    <%#  Search button %>
    <div>
      <%= link_to cinemas_path, class: "bottom_navbar-link #{'active' if current_page?(cinemas_path) || current_page?(map_path) || (params[:controller] == 'cinemas' && params[:action] == 'show')}" do %>
        <i class="fas fa-search"></i>
      <% end %>
    </div>

    <%# Favourites button %>
    <div>
      <%= link_to favourites_path, class: "bottom_navbar-link #{'active' if current_page?(favourites_path)}" do %>
        <i class="fas fa-star"></i>
      <% end %>
    </div>  

    <%# Map button%>
    <%#= link_to map_path, class: "bottom_navbar-link #{'active' if current_page?(map_path)}" do %>
      <%# <i class="fa-solid fa-map"></i> %>
    <%# end %>

    <%# Notifications button %>
    <div>
      <%= turbo_stream_from "notification_dot", current_user %>

      <%= link_to notifications_path, class: "bottom_navbar-link position-relative #{'active' if current_page?(notifications_path)}" do %>
        <i class="fas fa-bell"></i>
        <%= render partial: "notifications/notification_dot", locals: { user: current_user } %>
      <% end %>
    </div>

    <%#  Profile buton %>
    <div>
      <%= link_to profile_path, class: "bottom_navbar-link #{'active' if current_page?(profile_path) && !current_user.profile_picture.attached?}" do %>
        <% if user_signed_in? && current_user.profile_picture.attached? %>
          <%= cl_image_tag current_user.profile_picture.key, alt: "Profile picture", class: "bottom_navbar-profile-pic" %>
        <% else %>
          <i class="fas fa-user"></i>
        <% end %>
      <% end %>
    </div>

  </div>
</nav>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header" style="position: sticky; top: 0; width: 100%;">
  <div class="container-fluid" style="justify-content: center;">
    <div class="header-logo">
      <%= link_to root_path do %>
        <h1>Seated</h1>
        <%= image_tag "seated-chair-no-background.png", alt:"Logo Seat", class: "header-logo-seat"%>
      <% end %>
    </div>
  </div>
</div>