config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#home"
  get "profile", to: "pages#profile", as: :profile
  get "map", to: "pages#map"

  resources :cinemas, only: [:index, :show] do

    resources :reviews, only: [:new, :create] do
      resources :comments, only: [:create, :destroy]
      resources :votes, only: [:create, :destroy]
    end
    resources :favourites, only: [:create, :destroy]
  end
  resources :reviews, only: [:edit, :update, :destroy]
  resources :favourites, only: [:index, :destroy]

  resources :notifications, only: [:index, :destroy] do
    member do
      patch :mark_as_read
    end
  end

  # get "favourites/index"
  # get "favourites/create"
  # get "favourites/destroy"
  # get "reviews/new"
  # get "reviews/create"
  # get "reviews/edit"
  # get "reviews/update"
  # get "reviews/destroy"
  # get "cinemas/index"
  # get "cinemas/show"

  # get "notifications/index"
  # get "notifications/create"
  # get "notifications/destroy"
  # get "comments/create"
  # get "comments/destroy"
  # get "votes/create"
  # get "votes/destroy"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/cinema.rb
class Cinema < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favourites

  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true
  validates :description, presence: true
  validates :average_rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5, allow_nil: true }
  # validates :image_url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), allow_blank: true }

  # geocoded_by :address
  # after_validation :geocode, if: :address_changed?

  geocoded_by :address
  after_validation :geocode, if:
  :will_save_change_to_address?

  include PgSearch::Model

  pg_search_scope :search_by_name_and_address,
                  against: %i[name address],
                  using: {
                    tsearch: { prefix: true },
                    trigram: { threshold: 0.1 }
                  }

  def update_average_rating
    self.average_rating = reviews.average(:rating).to_f.round(1)
    save if average_rating_changed?
  end
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_cinema, only: [:show]

  def index # rubocop:disable Metrics/MethodLength
    if params[:query].present?
      @cinemas = Cinema.search_by_name_and_address(params[:query])
                       .order(Arel.sql("COALESCE(average_rating, 0) DESC"))
    else
      params[:sorted_by]
      @cinemas = Cinema.all
                       .order(Arel.sql("COALESCE(average_rating, 0) DESC"))
    end

    respond_to do |format|
      format.html
      format.json { render json: @cinemas.as_json(only: %i[id name address image_url description average_rating]) }
    end
  end

  def show
    @reviews = @cinema.reviews

    case params[:filter]
    when "rating_high_to_low"
      @reviews = @reviews.order(rating: :desc)
    when "rating_low_to_high"
      @reviews = @reviews.order(rating: :asc)
    when "date_oldest"
      @reviews = @reviews.order(created_at: :asc)
    else # Default to newest first
      @reviews = @reviews.order(created_at: :desc)
    end
  end

  private

  def set_cinema
    @cinema = Cinema.find(params[:id])
  end
end

app/views/cinemas/_cinema_search_list.html.erb
<div class="cinema-cards">
  <% cinemas.each do |cinema|%>
    <%= link_to cinema_path(cinema) do %>
      <div class="cinema-card">

        <div class=cinema-card-location>
          <h1><%= cinema.name %></h1>
          <h5><%= cinema.address %></h5>
        </div>

        <div class="cinema-card-image">
          <img src="<%= cinema.image_url %>" alt="<%= cinema.name%>" width=300px>
        </div>

        <div class="cinema-card-extras">
          <p><%= cinema.description %></p>

          <div class="cinema-list-average-rating">
            <% if cinema.average_rating.present? %>
              <% rounded_rating = cinema.average_rating.floor %>
              <% partial_rating = (cinema.average_rating % 1).round(1) %>

              <% # Render the full rating images as red rating images %>
              <% rounded_rating.times do %>
                <%= image_tag 'seated-emoji.png', alt: 'Red Rating Emoji', class: 'red-rating-image' %>
              <% end %>

              <% # Render the half image as a half red rating image %>
              <% if partial_rating >= 0.5 %>
                <%= image_tag 'seated-emoji.png', alt: 'Half Red Rating Emoji', class: 'half-red-rating-image' %>
              <% end %>

              <span class="average-rating-number">(<%= cinema.average_rating.round(1) %>)</span>
            <% else %>
              <span class="average-rating-number">No reviews yet</span>
            <% end %>
          </div>

        </div>

      </div>
    <% end %>
  <% end %>

</div>

app/views/cinemas/_list.html.erb
<div class="cinema-cards">
  <% cinemas.each do |cinema|%>
    <%= link_to cinema_path(cinema) do %>
      <div class="cinema-card">

        <div class=cinema-card-location>
          <h1><%= cinema.name %></h1>
          <h5><%= cinema.address %></h5>
        </div>

        <div class="cinema-card-image">
          <img src="<%= cinema.image_url %>" alt="<%= cinema.name%>" width=300px>
        </div>

        <div class="cinema-card-extras">
          <p><%= cinema.description %></p>
          <%# <p> Average rating:  %>
            <%#= cinema.average_rating.present? ? cinema.average_rating.round(1) : 'No reviews yet' </p> %>

          <div class="cinema-list-average-rating">
            <% if cinema.average_rating.present? %>
              <% rounded_rating = cinema.average_rating.floor %>
              <% partial_rating = (cinema.average_rating % 1).round(1) %>

              <% # Render the full rating images as red rating images %>
              <% rounded_rating.times do %>
                <%= image_tag 'seated-emoji.png', alt: 'Red Rating Emoji', class: 'red-rating-image' %>
              <% end %>

              <% # Render the half image as a half red rating image %>
              <% if partial_rating >= 0.5 %>
                <%= image_tag 'seated-emoji.png', alt: 'Half Red Rating Emoji', class: 'half-red-rating-image' %>
              <% end %>

              <span class="average-rating-number">(<%= cinema.average_rating.round(1) %>)</span>
            <% else %>
              <span class="average-rating-number">No reviews yet</span>
            <% end %>
          </div>

        </div>

      </div>
    <% end %>
  <% end %>

</div>

app/views/cinemas/_review.html.erb
<div class="cinema-review-card">
  <%= link_to cinema_path(review.cinema) do %>
    <div class="review-card-user">
      <% if review.user.profile_picture.attached? %>
        <%= cl_image_tag review.user.profile_picture.key, class: "review-profile-pic" %>
      <% else %>
        <%= image_tag "profile-icon.jpg", alt: "Profile picture", class: "review-profile-pic" %>
      <% end %>
      <p><%= review.user.username %></p>
    </div>
    <div class="review-name-date">
      <p><strong><%= review.cinema.name %></strong></p>
      <p><%= review.created_at.strftime("%e/%m/%y") %></p>
    </div>
    <div class="review-screen-details">
      <p>
        <span class="review-screen-details-icon">
          <%= image_tag('cinema-screen-emoji.jpg', alt: 'Screen icon', class: 'review-icon-class') %>
        </span>
        <span class="review-form-data"><strong><%= review.screen %></strong></span>
      </p>

      <p>
        <span class="review-screen-details-icon">
          <%= image_tag('seated-emoji-original.png', alt: 'Seated icon', class: 'review-icon-class') %>
        </span>
        <span class="review-form-data"><strong><%= review.seat %></strong></span>
      </p>

      <p>
        <span class="review-screen-details-icon">
          <%= image_tag('seated-emoji-gold.png', alt: 'Seated icon gold', class: 'review-icon-class') %>
        </span>
        <span class="review-form-data"><strong><%= review.pref_seat %></strong></span>
      </p>
    </div>
  <% end %>
    <div class="review-card-content">
      <% if review.photos.attached? %>
        <div class="review-images">
          <a href="#imageModal-<%= review.id %>" data-bs-toggle="modal" data-bs-target="#imageModal-<%= review.id %>">
            <%# First photo only as the thumbnail %>
            <%= cl_image_tag review.photos.first.key, class: "img-thumbnail review-image" %>
          </a>

            <!-- Modal with a carousel for all photos -->
          <div class="modal fade" id="imageModal-<%= review.id %>" tabindex="-1" aria-labelledby="imageModalLabel-<%= review.id %>" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-body">
                  <!-- Bootstrap carousel for sliding between images -->
                  <div id="carousel-<%= review.id %>" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                      <% review.photos.each_with_index do |photo, index| %>
                        <div class="carousel-item <%= 'active' if index == 0 %>">
                          <%= cl_image_tag photo.key, class: "d-block w-100 img-fluid"  %>
                        </div>
                      <% end %>
                    </div>

                    <%# Previous/Next carousel controls. Condition - only show if more than one image %>
                    <% if review.photos.count > 1 %>
                      <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= review.id %>" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= review.id %>" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                      </button>
                    <% end %>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-gradient" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <%= link_to cinema_path(review.cinema) do %>
        <div class="review-text">
          <p>"<%= review.content %>"</p>
        </div>
      <% end %>
    </div>

  <%= link_to cinema_path(review.cinema) do %>
    <div class="review-rating-scale">

      <div class="review-card-rating">
        <% if review.rating.present? %>
          <% rounded_rating = review.rating.floor %>
          <% partial_rating = (review.rating % 1).round(1) %>

          <% # Render the full rating images as red rating images %>
          <% rounded_rating.times do %>
            <%= image_tag 'seated-emoji.png', alt: 'Red Rating Emoji', class: 'red-rating-image' %>
          <% end %>

          <% # Render the half image as a half red rating image %>
          <% if partial_rating >= 0.5 %>
            <%= image_tag 'seated-emoji.png', alt: 'Half Red Rating Emoji', class: 'half-red-rating-image' %>
          <% end %>

          <span class="review-rating-number">(<%= review.rating.round(1) %>)</span>
        <% else %>
          <span class="review-rating-number">No rating provided</span>
        <% end %>
      </div>

    </div>
  <% end%>

  <div class="cinema-vote-comment">
    <% if user_signed_in? %>
    <div class="review-vote" id="toggle-vote-<%= review.id %>">
      <%= render 'votes/toggle_button', review: review %>
    </div>
    <%# comments %>
    <div class="review-comment">

      <p>
        <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#commentsModal-<%= review.id %>">
          Show Comments
        </button>
        <span id="comment-count-<%= review.id %>">(<%= review.comments.count %>)</span>
        <%= turbo_stream_from "review_#{review.id}_comments" %>
      </p>

      <!-- Modal for Comments -->
      <div class="modal fade" id="commentsModal-<%= review.id %>" tabindex="-1" aria-labelledby="commentsModalLabel-<%= review.id %>" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content" style="max-height: 50vh; overflow: hidden;">
            <div class="modal-header pb-0">
              <div class="modal-title" id="commentsModalLabel-<%= review.id %>">
                <h5 class="mb-1">Comments for review:</h5>
                <h6 class="text-muted">"<%= review.content %>"</h6>
              </div>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="overflow-y: auto;">



              <%= simple_form_for [cinema, review, Comment.new], html: { class: "live-comment-form d-flex", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } } do |form| %>
                <div class="form-floating">
                  <%= form.input :content, as: :text, label: false, placeholder: "Your Comment", input_html: { rows: 3 }, wrapper: false %>
                  <label for="<%= form.object_name %>_content">Your Comment</label>
                </div>
                <%= form.button :submit, 'Send', class: 'btn btn-primary' %>
              <% end %>

              <div id="comments-<%= review.id %>" class="comments">
                <%= render partial: 'comments/comment', collection: review.comments.order(created_at: :desc), as: :comment, locals: { user: current_user } %>
              </div>
              
            </div>
          </div>
        </div>
      </div>

    </div>
    <%# <div class="comment-sign-in"> %>
      <% else %>
          <p><%= link_to 'Sign in', new_user_session_path, class: 'btn btn-gradient' %>&nbsp; to vote & comment</p>
      <% end %>
    <%# </div> %>
  </div>
</div>

app/views/cinemas/_top_picks.html.erb
<div class="<%= container_class %>">
  <h2><%= heading %></h2>

  <% if cinemas.any? %>
    <% cinemas.each do |cinema| %>
      <%= link_to cinema_path(cinema), class: "top-pick-card" do %>
        <img src="<%= cinema.image_url %>" />
        <div class="top-pick-details">
          <h4><%= cinema.name %></h4>
          <p><%= cinema.address %></p>

          <div class="cinema-average-rating">
            <% if cinema.average_rating.present? %>
              <% rounded_rating = cinema.average_rating.floor %>
              <% partial_rating = (cinema.average_rating % 1).round(1) %>

              <%# Render the full rating images as red rating images %>
              <% rounded_rating.times do %>
                <%= image_tag 'seated-emoji.png', alt: 'Red Rating Emoji', class: 'red-rating-image' %>
              <% end %>

              <%# Render the half image as a half red rating image %>
              <% if partial_rating >= 0.5 %>
                <%= image_tag 'seated-emoji.png', alt: 'Half Red Rating Emoji', class: 'half-red-rating-image' %>
              <% end %>

              <span class="average-rating-number">(<%= cinema.average_rating.round(1) %>)</span>
            <% else %>
              <span class="average-rating-number">No reviews yet</span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <p class="no-review-message">Go on, review something...</p>
  <% end %>
</div>

app/views/cinemas/index.html.erb
<div class="cinema-index-background" data-seated-emoji-path="<%= asset_path('seated-emoji.png') %>"> 
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="cinema-index-contents" data-controller="autocomplete">
          <div class="index-search" >
            <%= form_tag cinemas_path, method: :get, class: "d-flex" do %>
              <%= text_field_tag :query,
                                  params[:query],
                                  class: "form-control",
                                  placeholder: "Where next?",
                                  data: {action: "keyup->autocomplete#search"}%>

              <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
            <% end %>

            <% if params[:query].present? %>
              <h2>Results for "<%= params[:query] %>"</h2>
            <% else %>
              <h2>Results</h2>
            <% end %>

            <div class="list-map-view">
              <div class="default-link <%= 'active' if request.path == cinemas_path %>">
                <%= link_to "List view", cinemas_path, class: "nav-link" %>
              </div>
              <div class="map-link  <%= 'active' if request.path == map_path %>">
                <%= link_to "Map view", map_path, class: "nav-link" %>
              </div>
            </div>   
          </div>

          <div data-autocomplete-target="results">
            <%= render "cinema_search_list", cinemas: @cinemas  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cinemas/show.html.erb
<div class="cinema-index-background">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="home-contents">
          <div class="cinema-show-card">

            <h1> <%= @cinema.name %> </h1>
            <p> <%= @cinema.address %> </p>
            <img src="<%= @cinema.image_url %>" alt="<%= @cinema.name %>">

            <div data-controller="favourite" class="cinema-show-links">

              <div class="show-add-favourite">

                <p class="review-new-btn">
                  <%= link_to "Add review", new_cinema_review_path(@cinema), class: 'review-new-btn' %>
                </p>

                <div id="toggle-favourite-<%= @cinema.id %>">
                  <%= render 'favourites/toggle_button', cinema: @cinema %>
                </div>

              </div>

              <div class="cinema-back-rating">
                <div class="show-back-btn">
                  <%= link_to "↩ All cinemas", cinemas_path %>
                </div>
                <div class="cinema-show-average">
                  <div class="cinema-average-rating">
                    <% if @cinema.average_rating.present? %>
                      <% rounded_rating = @cinema.average_rating.floor %>
                      <% partial_rating = (@cinema.average_rating % 1).round(1) %>

                      <% # Render the full rating images as red rating images %>
                      <% rounded_rating.times do %>
                        <%= image_tag 'seated-emoji.png', alt: 'Red Rating Emoji', class: 'red-rating-image' %>
                      <% end %>

                      <% # Render the half image as a half red rating image %>
                      <% if partial_rating >= 0.5 %>
                        <%= image_tag 'seated-emoji.png', alt: 'Half Red Rating Emoji', class: 'half-red-rating-image' %>
                      <% end %>

                      <span class="average-rating-number">(<%= @cinema.average_rating.round(1) %>)</span>
                    <% else %>
                      <span class="average-rating-number">No reviews yet</span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="cinema-review-cards">
            <h2> Our community </h2>

            <div class="review-filters">
              <%= form_with(url: cinema_path(@cinema), method: :get, local: false, data: { turbo_frame: "reviews" }, class: "filter-form") do |f| %>
                <%= f.label :filter, "Filter:" %>
                <%= f.select :filter, options_for_select([
                    ["Newest - oldest", "date_newest"],
                    ["Oldest - newest", "date_oldest"],
                    ["Rating: high - low", "rating_high_to_low"],
                    ["Rating: low - high", "rating_low_to_high"]
                  ], selected: params[:filter] || "date_newest"),
                  {}, class: "form-select d-inline-block w-auto" %>
                <%= f.submit "Apply", class: "btn btn-primary" %>
              <% end %>
            </div>

            <turbo-frame id="reviews">
              <% @reviews.each do |review| %>
                  <%= render partial: 'cinemas/review', locals: { review: review, cinema: @cinema } %>
              <% end %>
            </turbo-frame>

          </div>

        </div>
      </div>
    </div>
  </div>
</div>